# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Cheers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cheers

  pod 'LBTAComponents'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod "RxGesture"
  pod 'Firebase/Auth'
  pod 'SnapKit', '~> 4.0.0'
  pod 'MaterialComponents'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'Onboard'
  pod 'DropDown'
  pod 'ALCameraViewController'

end
